export const menu = [
  {
    id: 1,
    title: "main",
    listItems: [
      {
        id: 1,
        title: "Homepage",
        url: "/",
        icon: "home.svg",
      },
      {
        id: 2,
        title: "Daily Entry",
        url: "/Daily",
        icon: "user.svg",
      },
    ],
  },
  {
    id: 2,
    title: "Overview",
    listItems: [
      {
        id: 1,
        title: "Employees",
        url: "/employees",
        icon: "user.svg",
      },
      {
        id: 2,
        title: "Machines",
        url: "/machines",
        icon: "product.svg",
      },
      {
        id: 3,
        title: "Jobs",
        url: "/jobs",
        icon: "order.svg",
      },
    ],
  },

  {
    id: 4,
    title: "overview",
    listItems: [
      {
        id: 1,
        title: "Tools",
        url: "/tools",
        icon: "setting.svg",
      },
      {
        id: 2,
        title: "Breakdown",
        url: "/breakdown",
        icon: "backup.svg",
      },
    ],
  },
  {
    id: 5,
    title: "analytics",
    listItems: [
      {
        id: 1,
        title: "Charts",
        url: "/chart",
        icon: "chart.svg",
      },
      {
        id: 2,
        title: "Toolchart",
        url: "/Toolchart",
        icon: "log.svg",
      },
    ],
  },
];

export const topDealUsers = [
  {
    id: 1,
    img: "mahesh babu.svg",
    username: "Mahesh Babu",
    email: "babu@gmail.com",
    amount: "3.668",
  },
  {
    id: 2,
    img: "prabhas.svg",
    username: "Prabhas",
    email: "darling@gmail.com",
    amount: "3.256",
  },
  {
    id: 3,
    img: "ram.svg",
    username: "Ram charan",
    email: "Ram@gmail.com",
    amount: "2.998",
  },
  {
    id: 4,
    img: "/allu arjun.svg",
    username: "ALLU Arjun",
    email: "ALLU@gmail.com",
    amount: "2.512",
  },
  {
    id: 5,
    img: "/yash.svg",
    username: "YASH",
    email: "Yash@gmail.com",
    amount: "2.134",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
    username: "Shah rakuh Khan",
    email: "khan@gmail.com",
    amount: "1.932",
  },

  {
    id: 7,
    img: "mahesh babu.svg",
    username: "Mahesh Babu",
    email: "babu@gmail.com",
    amount: "3.668",
  },
  {
    id: 8,
    img: "prabhas.svg",
    username: "Prabhas",
    email: "darling@gmail.com",
    amount: "3.256",
  },
  {
    id: 9,
    img: "ram.svg",
    username: "Ram charan",
    email: "Ram@gmail.com",
    amount: "2.998",
  },
];
export const employeesData = [
  {
    id: 1,
    ssn: "123-45-6789",
    name: "Jon Snow",
    address: "Winterfell",
    efficiency: 85,
    phoneNumber: "555-1234",
  },
  {
    id: 2,
    ssn: "234-56-7890",
    name: "Cersei Lannister",
    address: "King's Landing",
    efficiency: 70,
    phoneNumber: "555-5678",
  },
  {
    id: 3,
    ssn: "345-67-8901",
    name: "Jaime Lannister",
    address: "King's Landing",
    efficiency: 75,
    phoneNumber: "555-9876",
  },
  {
    id: 4,
    ssn: "456-78-9012",
    name: "Arya Stark",
    address: "Winterfell",
    efficiency: 90,
    phoneNumber: "555-4321",
  },
  {
    id: 5,
    ssn: "567-89-0123",
    name: "Daenerys Targaryen",
    address: "Dragonstone",
    efficiency: 80,
    phoneNumber: "555-8765",
  },
  {
    id: 6,
    ssn: "678-90-1234",
    name: "Melisandre",
    address: "Asshai",
    efficiency: 95,
    phoneNumber: "555-2345",
  },
  {
    id: 7,
    ssn: "789-01-2345",
    name: "Ferrara Clifford",
    address: "Unknown",
    efficiency: 60,
    phoneNumber: "555-6789",
  },
  {
    id: 8,
    ssn: "890-12-3456",
    name: "Rossini Frances",
    address: "Unknown",
    efficiency: 78,
    phoneNumber: "555-3456",
  },
  {
    id: 9,
    ssn: "901-23-4567",
    name: "Harvey Roxie",
    address: "Unknown",
    efficiency: 85,
    phoneNumber: "555-9012",
  },

  {
    id: 10,
    ssn: "012-34-5678",
    name: "Sansa Stark",
    address: "Winterfell",
    efficiency: 88,
    phoneNumber: "555-7654",
  },
  {
    id: 11,
    ssn: "123-45-6780",
    name: "Tyrion Lannister",
    address: "Casterly Rock",
    efficiency: 82,
    phoneNumber: "555-2109",
  },

  {
    id: 12,
    ssn: "234-56-7890",
    name: "Cersei Lannister",
    address: "King's Landing",
    efficiency: 70,
    phoneNumber: "555-5678",
  },
  {
    id: 13,
    ssn: "345-67-8901",
    name: "Jaime Lannister",
    address: "King's Landing",
    efficiency: 75,
    phoneNumber: "555-9876",
  },
  {
    id: 14,
    ssn: "456-78-9012",
    name: "Arya Stark",
    address: "Winterfell",
    efficiency: 90,
    phoneNumber: "555-4321",
  },
  {
    id: 15,
    ssn: "567-89-0123",
    name: "Daenerys Targaryen",
    address: "Dragonstone",
    efficiency: 80,
    phoneNumber: "555-8765",
  },
  {
    id: 16,
    ssn: "678-90-1234",
    name: "Melisandre",
    address: "Asshai",
    efficiency: 95,
    phoneNumber: "555-2345",
  },
  {
    id: 17,
    ssn: "789-01-2345",
    name: "Ferrara Clifford",
    address: "Unknown",
    efficiency: 60,
    phoneNumber: "555-6789",
  },
  {
    id: 18,
    ssn: "890-12-3456",
    name: "Rossini Frances",
    address: "Unknown",
    efficiency: 78,
    phoneNumber: "555-3456",
  },
  {
    id: 19,
    ssn: "901-23-4567",
    name: "Harvey Roxie",
    address: "Unknown",
    efficiency: 85,
    phoneNumber: "555-9012",
  },
  {
    id: 20,
    ssn: "012-34-5678",
    name: "Sansa Stark",
    address: "Winterfell",
    efficiency: 88,
    phoneNumber: "555-7654",
  },
  {
    id: 21,
    ssn: "123-45-6780",
    name: "Tyrion Lannister",
    address: "Casterly Rock",
    efficiency: 82,
    phoneNumber: "555-2109",
  },
  {
    id: 22,
    ssn: "234-56-7891",
    name: "Bran Stark",
    address: "Winterfell",
    efficiency: 92,
    phoneNumber: "555-1122",
  },
];

export const ToolsData = [
  {
    id: 1,
    name: "Hammer",
    code: "HAM001",
    quantity: 10,
    maxLength: "12 inches",
    cost: "$10",
  },
  {
    id: 2,
    name: "Screwdriver",
    code: "SCRD002",
    quantity: 15,
    maxLength: "8 inches",
    cost: "$5",
  },
  {
    id: 3,
    name: "Wrench",
    code: "WRN003",
    quantity: 8,
    maxLength: "10 inches",
    cost: "$8",
  },
  {
    id: 4,
    name: "Pliers",
    code: "PLR004",
    quantity: 12,
    maxLength: "6 inches",
    cost: "$6",
  },
  {
    id: 5,
    name: "Drill",
    code: "DRL005",
    quantity: 5,
    maxLength: "14 inches",
    cost: "$20",
  },
  {
    id: 5,
    name: "Drill",
    code: "DRL005",
    quantity: 5,
    maxLength: "14 inches",
    cost: "$20",
  },
  {
    id: 5,
    name: "Drill",
    code: "DRL005",
    quantity: 5,
    maxLength: "14 inches",
    cost: "$20",
  },
  {
    id: 5,
    name: "Drill",
    code: "DRL005",
    quantity: 5,
    maxLength: "14 inches",
    cost: "$20",
  },
  {
    id: 5,
    name: "Drill",
    code: "DRL005",
    quantity: 5,
    maxLength: "14 inches",
    cost: "$20",
  },

  {
    id: 5,
    name: "Drill",
    code: "DRL005",
    quantity: 5,
    maxLength: "14 inches",
    cost: "$20",
  },
  {
    id: 5,
    name: "Drill",
    code: "DRL005",
    quantity: 5,
    maxLength: "14 inches",
    cost: "$20",
  },
  {
    id: 5,
    name: "Drill",
    code: "DRL005",
    quantity: 5,
    maxLength: "14 inches",
    cost: "$20",
  },
  {
    id: 5,
    name: "Drill",
    code: "DRL005",
    quantity: 5,
    maxLength: "14 inches",
    cost: "$20",
  },
];

export const breakdownData = [
  {
    date: "2024-03-15",
    lengthUsed: 10,
    expectedLengthRemaining: 90,
    replacedBy: "John Doe",
    reason: "Wear and tear",
    changeTime: "10:30 AM",
    hoursIntoShift: 2,
    machineId: "M001",
    toolCode: "T001",
  },
  {
    date: "2024-03-16",
    lengthUsed: 15,
    expectedLengthRemaining: 85,
    replacedBy: "Jane Smith",
    reason: "Maintenance",
    changeTime: "11:45 AM",
    hoursIntoShift: 3,
    machineId: "M002",
    toolCode: "T002",
  },
  {
    date: "2024-03-15",
    lengthUsed: 10,
    expectedLengthRemaining: 90,
    replacedBy: "John Doe",
    reason: "Wear and tear",
    changeTime: "10:30 AM",
    hoursIntoShift: 2,
    machineId: "M001",
    toolCode: "T001",
  },
  {
    date: "2024-03-15",
    lengthUsed: 10,
    expectedLengthRemaining: 90,
    replacedBy: "John Doe",
    reason: "Wear and tear",
    changeTime: "10:30 AM",
    hoursIntoShift: 2,
    machineId: "M001",
    toolCode: "T001",
  },
  {
    date: "2024-03-15",
    lengthUsed: 10,
    expectedLengthRemaining: 90,
    replacedBy: "John Doe",
    reason: "Wear and tear",
    changeTime: "10:30 AM",
    hoursIntoShift: 2,
    machineId: "M001",
    toolCode: "T001",
  },
  {
    date: "2024-03-15",
    lengthUsed: 10,
    expectedLengthRemaining: 90,
    replacedBy: "John Doe",
    reason: "Wear and tear",
    changeTime: "10:30 AM",
    hoursIntoShift: 2,
    machineId: "M001",
    toolCode: "T001",
  },
  {
    date: "2024-03-15",
    lengthUsed: 10,
    expectedLengthRemaining: 90,
    replacedBy: "John Doe",
    reason: "Wear and tear",
    changeTime: "10:30 AM",
    hoursIntoShift: 2,
    machineId: "M001",
    toolCode: "T001",
  },
  {
    date: "2024-03-15",
    lengthUsed: 10,
    expectedLengthRemaining: 90,
    replacedBy: "John Doe",
    reason: "Wear and tear",
    changeTime: "10:30 AM",
    hoursIntoShift: 2,
    machineId: "M001",
    toolCode: "T001",
  },
  {
    date: "2024-03-15",
    lengthUsed: 10,
    expectedLengthRemaining: 90,
    replacedBy: "John Doe",
    reason: "Wear and tear",
    changeTime: "10:30 AM",
    hoursIntoShift: 2,
    machineId: "M001",
    toolCode: "T001",
  },
  {
    date: "2024-03-15",
    lengthUsed: 10,
    expectedLengthRemaining: 90,
    replacedBy: "John Doe",
    reason: "Wear and tear",
    changeTime: "10:30 AM",
    hoursIntoShift: 2,
    machineId: "M001",
    toolCode: "T001",
  },
  {
    date: "2024-03-15",
    lengthUsed: 10,
    expectedLengthRemaining: 90,
    replacedBy: "John Doe",
    reason: "Wear and tear",
    changeTime: "10:30 AM",
    hoursIntoShift: 2,
    machineId: "M001",
    toolCode: "T001",
  },
  {
    date: "2024-03-15",
    lengthUsed: 10,
    expectedLengthRemaining: 90,
    replacedBy: "John Doe",
    reason: "Wear and tear",
    changeTime: "10:30 AM",
    hoursIntoShift: 2,
    machineId: "M001",
    toolCode: "T001",
  },
  {
    date: "2024-03-15",
    lengthUsed: 10,
    expectedLengthRemaining: 90,
    replacedBy: "John Doe",
    reason: "Wear and tear",
    changeTime: "10:30 AM",
    hoursIntoShift: 2,
    machineId: "M001",
    toolCode: "T001",
  },

  // Add more breakdown data as needed
];
export const JobsData = [
  {
    Job_id: 1,
    name: "Job 1",
    length: "10",
    holesCount: "5",
    toolCode: "TC001",
  },
  {
    Job_id: 2,
    name: "Job 2",
    length: "15",
    holesCount: "8",
    toolCode: "TC002",
  },
  {
    Job_id: 3,
    name: "Job 3",
    length: "20",
    holesCount: "10",
    toolCode: "TC003",
  },
  {
    Job_id: 4,
    name: "Job 4",
    length: "12",
    holesCount: "6",
    toolCode: "TC004",
  },
  {
    Job_id: 5,
    name: "Job 5",
    length: "18",
    holesCount: "7",
    toolCode: "TC005",
  },
  {
    Job_id: 6,
    name: "Job 6",
    length: "25",
    holesCount: "12",
    toolCode: "TC006",
  },
  {
    Job_id: 7,
    name: "Job 7",
    length: "30",
    holesCount: "15",
    toolCode: "TC007",
  },
  {
    Job_id: 8,
    name: "Job 8",
    length: "22",
    holesCount: "9",
    toolCode: "TC008",
  },
  {
    Job_id: 9,
    name: "Job 9",
    length: "28",
    holesCount: "14",
    toolCode: "TC009",
  },
  {
    Job_id: 10,
    name: "Job 10",
    length: "35",
    holesCount: "18",
    toolCode: "TC010",
  },
  {
    Job_id: 11,
    name: "Job 11",
    length: "40",
    holesCount: "20",
    toolCode: "TC011",
  },
];

export const MachinesData = [
  {
    id: 1,
    name: "Machine 1",
  },
  {
    id: 2,
    name: "Machine 2",
  },
  {
    id: 3,
    name: "Machine 3",
  },
  {
    id: 4,
    name: "Machine 4",
  },
  {
    id: 5,
    name: "Machine 5",
  },
  {
    id: 6,
    name: "Machine 6",
  },
  {
    id: 7,
    name: "Machine 7",
  },
  {
    id: 8,
    name: "Machine 8",
  },
];
